# Optimized JVM flags for better build performance.
org.gradle.jvmargs=-Xss512k -Xms2m -Xmx2g -Xlog:async -XX:+UseTransparentHugePages -XX:MaxDirectMemorySize=512m -XX:ReservedCodeCacheSize=384m -Djdk.nio.maxCachedBufferSize=262144 -XX:AllocatePrefetchStyle=3 -XX:+UseStringDeduplication -XX:+UseParallelGC -XX:+AllowParallelDefineClass -XX:+PerfDisableSharedMem -XX:+DisableExplicitGC -Djdk.util.jar.enableMultiRelease=force -Djava.net.preferIPv4Stack=true -Duser.language=en -Duser.country=US -XX:-PrintWarnings -XX:ThreadPriorityPolicy=1 -XX:TieredStopAtLevel=1 -XX:+HeapDumpOnOutOfMemoryError -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+IgnoreUnrecognizedVMOptions -XX:+UseCompactObjectHeaders

# Parallel task execution
org.gradle.parallel=true

# Build caching
org.gradle.caching=true

# Configuration cache
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.encryption=false
org.gradle.configureondemand=true
